// Generated by gencpp from file custom_msgs/coord.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_COORD_H
#define CUSTOM_MSGS_MESSAGE_COORD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace custom_msgs
{
template <class ContainerAllocator>
struct coord_
{
  typedef coord_<ContainerAllocator> Type;

  coord_()
    : x(0)
    , y(0)
    , z(0)  {
    }
  coord_(const ContainerAllocator& _alloc)
    : x(0)
    , y(0)
    , z(0)  {
  (void)_alloc;
    }



   typedef int32_t _x_type;
  _x_type x;

   typedef int32_t _y_type;
  _y_type y;

   typedef int32_t _z_type;
  _z_type z;





  typedef boost::shared_ptr< ::custom_msgs::coord_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msgs::coord_<ContainerAllocator> const> ConstPtr;

}; // struct coord_

typedef ::custom_msgs::coord_<std::allocator<void> > coord;

typedef boost::shared_ptr< ::custom_msgs::coord > coordPtr;
typedef boost::shared_ptr< ::custom_msgs::coord const> coordConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msgs::coord_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msgs::coord_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace custom_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'custom_msgs': ['/home/isaac/Desktop/IGVC_workspace/ros_initial/igvc_ws/src/custom_msgs/msg', '/home/isaac/Desktop/IGVC_workspace/ros_initial/igvc_ws/src/custom_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::coord_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::coord_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::coord_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::coord_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::coord_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::coord_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msgs::coord_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3cb41a2c4416de195dbb95b7777a06fb";
  }

  static const char* value(const ::custom_msgs::coord_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3cb41a2c4416de19ULL;
  static const uint64_t static_value2 = 0x5dbb95b7777a06fbULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msgs::coord_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msgs/coord";
  }

  static const char* value(const ::custom_msgs::coord_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msgs::coord_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 x\n\
int32 y\n\
int32 z\n\
";
  }

  static const char* value(const ::custom_msgs::coord_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msgs::coord_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct coord_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msgs::coord_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msgs::coord_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int32_t>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<int32_t>::stream(s, indent + "  ", v.z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_COORD_H
